// <auto-generated />
using FurnitureStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FurnitureStore.Migrations
{
    [DbContext(typeof(FurnitureDbContext))]
    [Migration("20260923141450_SeedFurnitureData")]
    partial class SeedFurnitureData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FurnitureStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Comfortable furniture for relaxing and entertaining.",
                            ImageUrl = "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
                            Name = "Living Room"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Create a calm and comfortable bedroom.",
                            ImageUrl = "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
                            Name = "Bedroom"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tables and chairs designed for gathering.",
                            ImageUrl = "https://images.unsplash.com/photo-1617806118233-18e1de247200",
                            Name = "Dining"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Stylish storage solutions for every room.",
                            ImageUrl = "https://images.unsplash.com/photo-1595428774223-ef52624120d2",
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Create a productive and beautiful workspace.",
                            ImageUrl = "https://images.unsplash.com/photo-1497366811353-6870744d04b2",
                            Name = "Office"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Furniture for enjoying your outdoor space.",
                            ImageUrl = "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0",
                            Name = "Outdoor"
                        });
                });

            modelBuilder.Entity("FurnitureStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A comfortable three-seater sofa with a modern minimalist design.",
                            ImageUrl = "https://images.unsplash.com/photo-1555041469-a586c61ea9bc",
                            IsFeatured = true,
                            Name = "Haven Three-Seater Sofa",
                            Price = 12999m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "A soft accent chair perfect for reading corners and living rooms.",
                            ImageUrl = "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c",
                            IsFeatured = true,
                            Name = "Luna Accent Chair",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Solid oak-inspired dining table with a clean contemporary finish.",
                            ImageUrl = "https://images.unsplash.com/photo-1617806118233-18e1de247200",
                            IsFeatured = true,
                            Name = "Oak Dining Table",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Minimal dining chair designed for everyday comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1503602642458-232111445657",
                            IsFeatured = false,
                            Name = "Modern Dining Chair",
                            Price = 1899m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "A simple upholstered bed frame with a soft neutral finish.",
                            ImageUrl = "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85",
                            IsFeatured = true,
                            Name = "Haven Queen Bed",
                            Price = 10999m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Compact bedside table with a drawer and open storage.",
                            ImageUrl = "https://images.unsplash.com/photo-1532372576444-dda954194ad0",
                            IsFeatured = false,
                            Name = "Oak Bedside Table",
                            Price = 2499m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Elegant storage cabinet for books, crockery and accessories.",
                            ImageUrl = "https://images.unsplash.com/photo-1595428774223-ef52624120d2",
                            IsFeatured = true,
                            Name = "Nordic Storage Cabinet",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            Description = "Clean and functional desk for your home office.",
                            ImageUrl = "https://images.unsplash.com/photo-1497366811353-6870744d04b2",
                            IsFeatured = false,
                            Name = "Minimal Desk",
                            Price = 4499m
                        });
                });

            modelBuilder.Entity("FurnitureStore.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("FurnitureStore.Models.Product", b =>
                {
                    b.HasOne("FurnitureStore.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FurnitureStore.Models.WishlistItem", b =>
                {
                    b.HasOne("FurnitureStore.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FurnitureStore.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
