FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore FurnitureStore.csproj

RUN dotnet publish FurnitureStore.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 80

ENTRYPOINT ["sh", "-c", "dotnet FurnitureStore.dll --urls http://0.0.0.0:${PORT:-80}"]